// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplateserver = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/tinder_system/v1/persons": {
            "get": {
                "summary": "Find the most N possible matched single people, where N is a request parameter.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "number of single person",
                        "name": "n",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "person name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "M or F",
                        "name": "gender",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "person height \u003e=",
                        "name": "heightGte",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "person height \u003c=",
                        "name": "heightLte",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.QuerySinglePeopleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "summary": "Add a new user to the matching system and find any possible matches for the new user",
                "parameters": [
                    {
                        "description": "params",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SinglePerson"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AddSinglePersonAndMatchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tinder_system/v1/persons/{name}": {
            "delete": {
                "summary": "Remove a user from the matching system so that the user cannot be matched anymore.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "person name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CommonResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AddSinglePersonAndMatchResponse": {
            "type": "object",
            "properties": {
                "matches": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SinglePerson"
                    }
                },
                "newUser": {
                    "$ref": "#/definitions/models.SinglePerson"
                }
            }
        },
        "models.CommonResponse": {
            "type": "object",
            "properties": {
                "result": {
                    "type": "string"
                }
            }
        },
        "models.ErrorDetails": {
            "type": "object",
            "required": [
                "code",
                "message"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "required": [
                "error"
            ],
            "properties": {
                "error": {
                    "$ref": "#/definitions/models.ErrorDetails"
                }
            }
        },
        "models.QuerySinglePeopleResponse": {
            "type": "object",
            "properties": {
                "matches": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SinglePerson"
                    }
                }
            }
        },
        "models.SinglePerson": {
            "type": "object",
            "properties": {
                "gender": {
                    "type": "string",
                    "example": "M or F"
                },
                "height": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "number_of_date": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfoserver holds exported Swagger Info so clients can modify it
var SwaggerInfoserver = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Tinder Matching System API",
	Description:      "",
	InfoInstanceName: "server",
	SwaggerTemplate:  docTemplateserver,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoserver.InstanceName(), SwaggerInfoserver)
}
